# Generated by Django 3.0.2 on 2020-02-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_order_food_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_table',
        ),
        migrations.AddField(
            model_name='order_food',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='order_food',
            name='person',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
