# Generated by Django 3.0.2 on 2020-02-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_post', models.CharField(max_length=100)),
                ('c_image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cu_name', models.CharField(max_length=50)),
                ('cu_review', models.CharField(max_length=1000)),
                ('cu_image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
