# Generated by Django 3.0.2 on 2020-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=1000)),
                ('date', models.DateField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
