# Generated by Django 3.0.2 on 2020-02-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='f_price',
            field=models.FloatField(default=0),
        ),
    ]
